# Generated by Django 5.2 on 2026-06-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneverificationcode',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
