"""
Django settings for plateforme_municipale project.

Generated by 'django startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta

# Chargement des variables d'environnement
load_dotenv()

# ============================================
# CONFIGURATION DE BASE
# ============================================

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("La variable d'environnement SECRET_KEY n'est pas définie !")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# SECURITY WARNING: define explicit allowed hosts in production!
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# ============================================
# APPLICATIONS INSTALLÉES
# ============================================

INSTALLED_APPS = [
    # Administration
    'admin_interface',
    'colorfield',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    
    # Éditeurs de texte
    'django_ckeditor_5',
    
    # Applications tierces
    'taggit',
    'django_filters',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'corsheaders',
    'phonenumber_field',
    
    # Applications locales
    'accounts',
    'etat_civil',
    'signature_electronique',
    'actualites',
    'annuaires',
    'archives',
    'paiements',
    'dechets',
    'activites',
    'dashboard',
    'dashboard_agent',
]

# ============================================
# ADMIN INTERFACE CONFIGURATION
# ============================================

X_FRAME_OPTIONS = 'SAMEORIGIN'
SILENCED_SYSTEM_CHECKS = [
    'security.W019', 
    'admin.E408', 
    'admin.E409', 
    'admin.E410', 
    'admin.E411', 
    'admin.E412'
]

# ============================================
# CONFIGURATION FRONTEND
# ============================================

# URL du frontend pour les redirections et liens
FRONTEND_URL = os.getenv('FRONTEND_URL', 'https://botmatmakak.cm')

# URLs de redirection
EMAIL_CONFIRMATION_URL = f"{FRONTEND_URL}/confirm-email/"
PASSWORD_RESET_URL = f"{FRONTEND_URL}/reset-password/"

# ============================================
# CONFIGURATION SIGNATURE ÉLECTRONIQUE
# ============================================

SIGNATURE_CONFIGURATION = {
    'niveau_requis_etat_civil': 2,
    'niveau_requis_archives': 1,
    'delai_validite_demande': 7,
    'MAX_SIGNATURES_PER_DAY': 100,
    'SESSION_TIMEOUT_MINUTES': 30,
}

# ============================================
# CONFIGURATION PAIEMENTS
# ============================================

# MTN Mobile Money
MTN_API_URL = os.getenv('MTN_API_URL', 'https://api.mtn.com/v1')
MTN_API_KEY = os.getenv('MTN_API_KEY')
MTN_API_SECRET = os.getenv('MTN_API_SECRET')
MTN_MERCHANT_CODE = os.getenv('MTN_MERCHANT_CODE')

# Orange Money
ORANGE_API_URL = os.getenv('ORANGE_API_URL', 'https://api.orange.com')
ORANGE_MERCHANT_CODE = os.getenv('ORANGE_MERCHANT_CODE')
ORANGE_ACCESS_TOKEN = os.getenv('ORANGE_ACCESS_TOKEN')

# ============================================
# AUTHENTIFICATION
# ============================================

# Custom user model
AUTH_USER_MODEL = 'accounts.Utilisateur'

# Authentication backends
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "accounts.backends.EmailOrUsernameBackend",
    "accounts.backends.PhoneBackend",
    "accounts.backends.TOTPBackend",
]

# URLs de redirection pour l'authentification
LOGIN_URL = '/api/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# ============================================
# ENDPOINTS PUBLICS (pour information uniquement)
# ============================================

PUBLIC_ENDPOINTS = [
    '/api/accounts/login/',
    '/api/accounts/register/',
    '/api/accounts/forgot-password/',
    '/api/accounts/reset-password/',
    '/api/accounts/verify-email/',
    '/api/accounts/resend-verification/',
    '/api/signature-electronique/demandes/signer_token/',
    '/api/archives/acces/consulter/',
]

# ============================================
# REST FRAMEWORK CONFIGURATION - VERSION SIMPLIFIÉE (Option 2)
# ============================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # ✅ MODIFICATION CLÉ : Utilisation de la permission native IsAuthenticated
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
    'NON_FIELD_ERRORS_KEY': 'error',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/day',
    },
}

# ============================================
# SIMPLE JWT CONFIGURATION
# ============================================

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(hours=24),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=7),
}

# ============================================
# REST FRAMEWORK EXTENSIONS
# ============================================

REST_FRAMEWORK_EXTENSIONS = {
    'DEFAULT_CACHE_RESPONSE_TIMEOUT': 60 * 15,  # 15 minutes
}

# ============================================
# CORS CONFIGURATION
# ============================================

# En développement, vous pouvez autoriser toutes les origines
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = os.getenv(
        'CORS_ALLOWED_ORIGINS',
        'https://botmatmakak.cm,https://www.botmatmakak.cm'
    ).split(',')

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# ============================================
# PHONE NUMBER CONFIGURATION
# ============================================

PHONENUMBERS_DEFAULT_REGION = 'CM'
PHONENUMBERS_DEFAULT_FORMAT = 'E164'

# ============================================
# EMAIL CONFIGURATION
# ============================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# Validation des configuration email en production
if not DEBUG and not all([EMAIL_HOST, EMAIL_HOST_USER, EMAIL_HOST_PASSWORD]):
    raise ValueError("Configuration email incomplète en production !")

# ============================================
# TWILIO CONFIGURATION (SMS)
# ============================================

TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN')
TWILIO_PHONE_NUMBER = os.getenv('TWILIO_PHONE_NUMBER')

# ============================================
# CKEDITOR 5 CONFIGURATION
# ============================================

CKEDITOR_5_UPLOAD_PATH = 'uploads/ckeditor5/'
CKEDITOR_5_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': {
            'items': [
                'heading', '|',
                'bold', 'italic', 'underline', 'strikethrough', '|',
                'link', '|',
                'bulletedList', 'numberedList', '|',
                'alignment', '|',
                'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', '|',
                'blockQuote', 'codeBlock', '|',
                'insertTable', 'mediaEmbed', '|',
                'undo', 'redo', '|',
                'removeFormat'
            ]
        },
        'language': 'fr',
        'heading': {
            'options': [
                {'model': 'paragraph', 'title': 'Paragraphe', 'class': 'ck-heading_paragraph'},
                {'model': 'heading1', 'view': 'h1', 'title': 'Titre 1', 'class': 'ck-heading_heading1'},
                {'model': 'heading2', 'view': 'h2', 'title': 'Titre 2', 'class': 'ck-heading_heading2'},
                {'model': 'heading3', 'view': 'h3', 'title': 'Titre 3', 'class': 'ck-heading_heading3'},
                {'model': 'heading4', 'view': 'h4', 'title': 'Titre 4', 'class': 'ck-heading_heading4'},
                {'model': 'heading5', 'view': 'h5', 'title': 'Titre 5', 'class': 'ck-heading_heading5'},
                {'model': 'heading6', 'view': 'h6', 'title': 'Titre 6', 'class': 'ck-heading_heading6'},
            ]
        },
        'fontSize': {
            'options': [9, 10, 11, 12, 14, 16, 18, 20, 22, 24, 28, 32, 36, 40],
            'supportAllValues': True
        },
        'fontFamily': {
            'options': [
                'default',
                'Arial, Helvetica, sans-serif',
                'Courier New, Courier, monospace',
                'Georgia, serif',
                'Lucida Sans Unicode, Lucida Grande, sans-serif',
                'Tahoma, Geneva, sans-serif',
                'Times New Roman, Times, serif',
                'Trebuchet MS, Helvetica, sans-serif',
                'Verdana, Geneva, sans-serif'
            ],
            'supportAllValues': True
        },
        'table': {
            'contentToolbar': [
                'tableColumn', 'tableRow', 'mergeTableCells',
                'tableProperties', 'tableCellProperties'
            ]
        },
        'htmlSupport': {
            'allow': [
                {'name': 'iframe', 'attributes': {'src': True, 'frameborder': True, 'allowfullscreen': True}},
                {'name': 'div', 'classes': True, 'styles': True},
                {'name': 'span', 'classes': True, 'styles': True},
                {'name': 'a', 'attributes': {'target': True, 'rel': True}},
                {'name': 'img', 'attributes': {'src': True, 'alt': True, 'width': True, 'height': True}},
            ]
        },
        'placeholder': 'Écrivez votre contenu ici...',
        'removePlugins': ['Title'],
    },
    'advanced': {
        'toolbar': {
            'items': [
                'heading', '|',
                'bold', 'italic', 'underline', 'strikethrough', '|',
                'link', '|',
                'bulletedList', 'numberedList', '|',
                'alignment', '|',
                'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', '|',
                'imageUpload', '|',
                'blockQuote', 'codeBlock', '|',
                'insertTable', 'mediaEmbed', '|',
                'undo', 'redo', '|',
                'removeFormat', 'sourceEditing'
            ]
        },
        'language': 'fr',
        'image': {
            'toolbar': [
                'imageTextAlternative', 
                'imageStyle:alignLeft', 
                'imageStyle:alignCenter', 
                'imageStyle:alignRight',
                'imageStyle:alignBlockLeft',
                'imageStyle:alignBlockRight',
                'linkImage'
            ],
            'styles': ['alignLeft', 'alignCenter', 'alignRight']
        },
        'mediaEmbed': {
            'previewsInData': True,
            'providers': [
                {
                    'name': 'youtube',
                    'url': r'^https?://(?:www\.)?(?:youtube\.com|youtu\.be)/',
                    'html': '<iframe width="560" height="315" src="https://www.youtube.com/embed/{id}" frameborder="0" allowfullscreen></iframe>'
                },
                {
                    'name': 'vimeo',
                    'url': r'^https?://(?:www\.)?vimeo\.com/',
                    'html': '<iframe src="https://player.vimeo.com/video/{id}" width="560" height="315" frameborder="0" allowfullscreen></iframe>'
                }
            ]
        },
        'table': {
            'contentToolbar': [
                'tableColumn', 'tableRow', 'mergeTableCells',
                'tableProperties', 'tableCellProperties'
            ]
        },
        'htmlSupport': {
            'allow': [
                {'name': 'iframe', 'attributes': {'src': True, 'frameborder': True, 'allowfullscreen': True}},
                {'name': 'div', 'classes': True, 'styles': True},
                {'name': 'span', 'classes': True, 'styles': True},
                {'name': 'a', 'attributes': {'target': True, 'rel': True}},
                {'name': 'img', 'attributes': {'src': True, 'alt': True, 'width': True, 'height': True}},
            ]
        },
        'placeholder': 'Écrivez votre contenu avancé ici...',
    }
}

# ============================================
# MIDDLEWARE
# ============================================

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ============================================
# TEMPLATES
# ============================================

ROOT_URLCONF = 'plateforme_municipale.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'plateforme_municipale.wsgi.application'

# ============================================
# DATABASE - POSTGRESQL
# ============================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'plateforme_municipale'),
        'USER': os.getenv('DB_USER', 'plateforme_user'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
        'OPTIONS': {
            'options': '-c search_path=public'
        },
        'CONN_MAX_AGE': 60,
    }
}

# Validation de la configuration base de données en production
if not DEBUG and not os.getenv('DB_PASSWORD'):
    raise ValueError("Le mot de passe de la base de données n'est pas défini en production !")

# ============================================
# PASSWORD VALIDATION
# ============================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ============================================
# INTERNATIONALIZATION
# ============================================

LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Africa/Douala'
USE_I18N = True
USE_TZ = True

# ============================================
# STATIC & MEDIA FILES
# ============================================

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Dossiers spécifiques
ARCHIVES_MEDIA_ROOT = os.path.join(MEDIA_ROOT, 'archives')
ANNUAIRES_MEDIA_ROOT = os.path.join(MEDIA_ROOT, 'annuaires')

# ============================================
# FILE UPLOAD CONFIGURATION
# ============================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATA_UPLOAD_MAX_NUMBER_FILES = 100
DATA_UPLOAD_MAX_FILE_SIZE = 10485760  # 10 MB

ALLOWED_ARCHIVE_EXTENSIONS = ['.pdf', '.jpg', '.jpeg', '.png', '.doc', '.docx', '.txt']

FILE_UPLOAD_HANDLERS = [
    'django.core.files.uploadhandler.MemoryFileUploadHandler',
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
]

# ============================================
# CACHE CONFIGURATION
# ============================================

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'plateforme-municipale-cache',
    },
    'archive_cache': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'archive_cache_table',
        'TIMEOUT': 3600,
    }
}

# ============================================
# SÉCURITÉ (Production)
# ============================================

if not DEBUG:
    # HTTPS
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Headers de sécurité
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    
    # HSTS
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Session
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    
    # Referrer Policy
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# ============================================
# LOGGING CONFIGURATION - CORRIGÉE
# ============================================

# Créer le dossier logs s'il n'existe pas
LOG_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple' if DEBUG else 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'django.log'),
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG' if DEBUG else 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['file'] if not DEBUG else ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'accounts': {
            'handlers': ['console', 'file'] if not DEBUG else ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'paiements': {
            'handlers': ['console', 'file'] if not DEBUG else ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}