# Generated by Django 5.2 on 2026-06-12 18:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CachetElectronique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='signatures/cachets/')),
                ('certificat', models.TextField(help_text='Certificat du cachet')),
                ('cle_privee', models.TextField(help_text='Clé privée du cachet (chiffrée)')),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Cachet électronique',
                'verbose_name_plural': 'Cachets électroniques',
            },
        ),
        migrations.CreateModel(
            name='ConfigurationSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_requis_etat_civil', models.IntegerField(choices=[(1, 'Signature simple'), (2, 'Signature avancée'), (3, 'Signature qualifiée')], default=1)),
                ('niveau_requis_archives', models.IntegerField(choices=[(1, 'Signature simple'), (2, 'Signature avancée'), (3, 'Signature qualifiée')], default=2)),
                ('niveau_requis_activites', models.IntegerField(choices=[(1, 'Signature simple'), (2, 'Signature avancée'), (3, 'Signature qualifiée')], default=1)),
                ('niveau_requis_dechets', models.IntegerField(choices=[(1, 'Signature simple'), (2, 'Signature avancée'), (3, 'Signature qualifiée')], default=1)),
                ('niveau_requis_marche_public', models.IntegerField(choices=[(1, 'Signature simple'), (2, 'Signature avancée'), (3, 'Signature qualifiée')], default=3)),
                ('delai_validite_demande', models.IntegerField(default=7, help_text='Délai en jours avant expiration des demandes')),
                ('delai_relance', models.IntegerField(default=2, help_text='Délai en jours avant relance')),
                ('cle_privee_systeme', models.TextField(blank=True, help_text='Clé privée du système (chiffrée)')),
                ('cle_publique_systeme', models.TextField(blank=True, help_text='Clé publique du système')),
                ('signature_automatique', models.BooleanField(default=False, help_text='Permet les signatures automatiques pour certains documents')),
                ('stockage_preuve', models.BooleanField(default=True, help_text='Stockage des preuves de signature')),
                ('horizon_archivage', models.IntegerField(default=10, help_text="Années d'archivage des signatures")),
                ('service_horodatage_url', models.URLField(blank=True, help_text="URL du service d'horodatage")),
                ('service_horodatage_token', models.CharField(blank=True, max_length=255)),
                ('cachet_actif', models.BooleanField(default=True, help_text='Apposer un cachet électronique')),
                ('cachet_image', models.ImageField(blank=True, null=True, upload_to='signatures/cachets/')),
            ],
            options={
                'verbose_name': 'Configuration de la signature',
                'verbose_name_plural': 'Configurations de la signature',
            },
        ),
        migrations.CreateModel(
            name='CertificatNumerique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificat', models.TextField(help_text='Certificat X.509 au format PEM')),
                ('cle_publique', models.TextField(help_text='Clé publique au format PEM')),
                ('cle_privee_chiffree', models.TextField(help_text='Clé privée chiffrée (AES-256)')),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('emetteur', models.CharField(default='Commune de Bot-Makak', max_length=200)),
                ('sujet_nom', models.CharField(blank=True, help_text='Nom complet du titulaire', max_length=200)),
                ('sujet_email', models.EmailField(blank=True, max_length=254)),
                ('sujet_organisation', models.CharField(blank=True, default='Commune de Bot-Makak', max_length=200)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('date_revocation', models.DateTimeField(blank=True, null=True)),
                ('est_valide', models.BooleanField(default=True)),
                ('est_revoque', models.BooleanField(default=False)),
                ('raison_revocation', models.TextField(blank=True)),
                ('niveau_confiance', models.IntegerField(choices=[(1, 'Signature simple'), (2, 'Signature avancée'), (3, 'Signature qualifiée')], default=1)),
                ('empreinte', models.CharField(blank=True, help_text='Empreinte SHA-256 du certificat', max_length=64)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificat_signature', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificat numérique',
                'verbose_name_plural': 'Certificats numériques',
            },
        ),
        migrations.CreateModel(
            name='DemandeSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_source', models.CharField(choices=[('etat_civil', 'État Civil'), ('archives', 'Archives'), ('activites', 'Activités'), ('dechets', 'Déchets'), ('deliberation', 'Délibération'), ('arrete', 'Arrêté'), ('paiements', 'Paiements'), ('marche_public', 'Marché Public'), ('contrat', 'Contrat')], max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=100)),
                ('document_titre', models.CharField(max_length=200)),
                ('document_contenu', models.TextField(help_text='Contenu du document à signer')),
                ('document_fichier', models.FileField(blank=True, null=True, upload_to='signatures/documents/%Y/%m/')),
                ('destinataire_email', models.EmailField(blank=True, max_length=254)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('message_personnalise', models.TextField(blank=True, help_text='Message joint à la demande')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de signature'), ('signe', 'Signé'), ('expire', 'Expiré'), ('annule', 'Annulé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('date_signature', models.DateTimeField(blank=True, null=True)),
                ('nb_relances', models.PositiveIntegerField(default=0)),
                ('derniere_relance', models.DateTimeField(blank=True, null=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_signature', to=settings.AUTH_USER_MODEL)),
                ('envoyeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures_envoyees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de signature',
                'verbose_name_plural': 'Demandes de signature',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RelanceSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_relance', models.DateTimeField(auto_now_add=True)),
                ('canal', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Notification push')], max_length=20)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('envoye', 'Envoyé'), ('echoue', 'Échoué')], default='envoye', max_length=20)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relances', to='signature_electronique.demandesignature')),
            ],
            options={
                'ordering': ['-date_relance'],
            },
        ),
        migrations.CreateModel(
            name='SignatureElectronique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_source', models.CharField(choices=[('etat_civil', 'État Civil'), ('archives', 'Archives'), ('activites', 'Activités'), ('dechets', 'Déchets'), ('deliberation', 'Délibération'), ('arrete', 'Arrêté'), ('paiements', 'Paiements'), ('marche_public', 'Marché Public'), ('contrat', 'Contrat')], max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=100)),
                ('document_titre', models.CharField(max_length=200)),
                ('document_hash', models.CharField(help_text='Hash SHA-256 du document', max_length=64)),
                ('document_contenu', models.TextField(blank=True, help_text='Contenu textuel du document signé')),
                ('signature_valeur', models.TextField(help_text='Valeur cryptographique de la signature')),
                ('type_signature', models.CharField(choices=[('manuscrite', 'Signature manuscrite'), ('electronique', 'Signature électronique simple'), ('avancee', 'Signature avancée'), ('qualifiee', 'Signature qualifiée')], default='electronique', max_length=20)),
                ('timestamp_signature', models.DateTimeField(auto_now_add=True)),
                ('horodatage', models.DateTimeField(default=django.utils.timezone.now)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('largeur', models.IntegerField(default=200)),
                ('hauteur', models.IntegerField(default=80)),
                ('signature_image', models.TextField(blank=True, help_text='Image de la signature (base64)')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('est_valide', models.BooleanField(default=True)),
                ('date_validation', models.DateTimeField(auto_now_add=True)),
                ('raison_signature', models.CharField(blank=True, help_text='Raison de la signature', max_length=255)),
                ('certificat_utilise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signature_electronique.certificatnumerique')),
                ('signataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signature électronique',
                'verbose_name_plural': 'Signatures électroniques',
                'ordering': ['-timestamp_signature'],
            },
        ),
        migrations.CreateModel(
            name='PreuveSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horodatage_externe', models.DateTimeField(help_text='Horodatage certifié par un tiers')),
                ('jeton_horodatage', models.TextField(help_text="Jetons d'horodatage (RFC 3161)")),
                ('empreinte_longue', models.CharField(help_text='Empreinte pour la conservation', max_length=255)),
                ('preuve_conservation', models.FileField(blank=True, null=True, upload_to='signatures/preuves/%Y/%m/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('signature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preuve', to='signature_electronique.signatureelectronique')),
            ],
            options={
                'verbose_name': 'Preuve de signature',
                'verbose_name_plural': 'Preuves de signature',
            },
        ),
        migrations.CreateModel(
            name='JournalSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('creation', 'Création de signature'), ('validation', 'Validation de signature'), ('verification', 'Vérification de signature'), ('rejet', 'Rejet de signature'), ('revocation_certificat', 'Révocation de certificat'), ('demande_envoyee', 'Demande envoyée'), ('demande_annulee', 'Demande annulée'), ('relance', 'Relance envoyée')], max_length=50)),
                ('commentaire', models.TextField(blank=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='signature_electronique.demandesignature')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='signature_electronique.signatureelectronique')),
            ],
            options={
                'verbose_name': 'Journal de signature',
                'verbose_name_plural': 'Journaux de signature',
                'ordering': ['-date_action'],
            },
        ),
        migrations.AddField(
            model_name='demandesignature',
            name='signature',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande', to='signature_electronique.signatureelectronique'),
        ),
        migrations.CreateModel(
            name='VerificationSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultat', models.BooleanField()),
                ('details', models.JSONField(default=dict)),
                ('date_verification', models.DateTimeField(auto_now_add=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='signature_electronique.signatureelectronique')),
                ('verificateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vérification de signature',
                'verbose_name_plural': 'Vérifications de signature',
                'ordering': ['-date_verification'],
            },
        ),
        migrations.AddIndex(
            model_name='certificatnumerique',
            index=models.Index(fields=['numero_serie'], name='signature_e_numero__c79381_idx'),
        ),
        migrations.AddIndex(
            model_name='certificatnumerique',
            index=models.Index(fields=['utilisateur', 'est_valide'], name='signature_e_utilisa_b87815_idx'),
        ),
        migrations.AddIndex(
            model_name='certificatnumerique',
            index=models.Index(fields=['date_expiration'], name='signature_e_date_ex_0832b1_idx'),
        ),
        migrations.AddIndex(
            model_name='signatureelectronique',
            index=models.Index(fields=['module_source', 'source_id'], name='signature_e_module__344c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='signatureelectronique',
            index=models.Index(fields=['signataire', 'timestamp_signature'], name='signature_e_signata_65555d_idx'),
        ),
        migrations.AddIndex(
            model_name='signatureelectronique',
            index=models.Index(fields=['document_hash'], name='signature_e_documen_e49448_idx'),
        ),
        migrations.AddIndex(
            model_name='signatureelectronique',
            index=models.Index(fields=['timestamp_signature'], name='signature_e_timesta_79772b_idx'),
        ),
        migrations.AddIndex(
            model_name='journalsignature',
            index=models.Index(fields=['signature', 'action'], name='signature_e_signatu_8aceaa_idx'),
        ),
        migrations.AddIndex(
            model_name='journalsignature',
            index=models.Index(fields=['date_action'], name='signature_e_date_ac_d7c31f_idx'),
        ),
        migrations.AddIndex(
            model_name='journalsignature',
            index=models.Index(fields=['utilisateur', 'date_action'], name='signature_e_utilisa_25c157_idx'),
        ),
        migrations.AddIndex(
            model_name='demandesignature',
            index=models.Index(fields=['token'], name='signature_e_token_95bde7_idx'),
        ),
        migrations.AddIndex(
            model_name='demandesignature',
            index=models.Index(fields=['statut', 'date_expiration'], name='signature_e_statut_c78db0_idx'),
        ),
        migrations.AddIndex(
            model_name='demandesignature',
            index=models.Index(fields=['destinataire', 'statut'], name='signature_e_destina_c41695_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationsignature',
            index=models.Index(fields=['signature', 'date_verification'], name='signature_e_signatu_d842f2_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationsignature',
            index=models.Index(fields=['resultat'], name='signature_e_resulta_2da00a_idx'),
        ),
    ]
