# Generated by Django 5.2 on 2026-06-12 18:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('orange', 'Orange Money'), ('virement', 'Virement bancaire'), ('cash', 'Cash physique'), ('carte', 'Carte bancaire'), ('portefeuille', 'Portefeuille citoyen')], max_length=20, unique=True)),
                ('nom', models.CharField(blank=True, help_text='Nom affiché', max_length=100)),
                ('est_actif', models.BooleanField(default=True)),
                ('ordre_affichage', models.PositiveIntegerField(default=0)),
                ('api_url', models.URLField(blank=True, null=True)),
                ('api_key', models.CharField(blank=True, max_length=200)),
                ('api_secret', models.CharField(blank=True, max_length=200)),
                ('merchant_code', models.CharField(blank=True, max_length=50)),
                ('rib', models.CharField(blank=True, max_length=50)),
                ('iban', models.CharField(blank=True, max_length=50)),
                ('bic', models.CharField(blank=True, max_length=20)),
                ('titulaire_compte', models.CharField(blank=True, max_length=200)),
                ('banque', models.CharField(blank=True, max_length=100)),
                ('frais_fixe', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('frais_pourcentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('taxe', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('montant_min', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_max', models.DecimalField(decimal_places=2, default=1000000, max_digits=10)),
                ('expiration_minutes', models.PositiveIntegerField(default=30, help_text="Délai d'expiration en minutes")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='paiements/logos/')),
            ],
            options={
                'verbose_name': 'Configuration de paiement',
                'verbose_name_plural': 'Configurations de paiement',
                'ordering': ['ordre_affichage', 'mode'],
            },
        ),
        migrations.CreateModel(
            name='FactureRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periode', models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('semestriel', 'Semestriel'), ('annuel', 'Annuel')], max_length=20)),
                ('jour_echeance', models.PositiveSmallIntegerField(help_text="Jour du mois pour l'échéance")),
                ('prochaine_echeance', models.DateField()),
                ('statut', models.CharField(choices=[('active', 'Active'), ('suspendue', 'Suspendue'), ('terminee', 'Terminée')], default='active', max_length=20)),
                ('dernier_paiement', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_recurrentes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facture récurrente',
                'verbose_name_plural': 'Factures récurrentes',
                'ordering': ['prochaine_echeance'],
            },
        ),
        migrations.CreateModel(
            name='PortefeuilleCitoyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('points_fidelite', models.IntegerField(default=0)),
                ('plafond', models.DecimalField(decimal_places=2, default=500000, help_text='Plafond maximum du portefeuille', max_digits=10)),
                ('est_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portefeuille', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portefeuille citoyen',
                'verbose_name_plural': 'Portefeuilles citoyens',
            },
        ),
        migrations.CreateModel(
            name='TransactionPaiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('module_source', models.CharField(choices=[('etat_civil', 'État Civil'), ('activites', 'Activités'), ('dechets', 'Déchets'), ('archives', 'Archives'), ('amendes', 'Amendes'), ('taxes', 'Taxes'), ('signatures', 'Signatures électroniques'), ('portefeuille', 'Portefeuille citoyen')], default='etat_civil', max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=100)),
                ('montant_net', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('frais', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxe', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode', models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('orange', 'Orange Money'), ('virement', 'Virement bancaire'), ('cash', 'Cash physique'), ('carte', 'Carte bancaire'), ('portefeuille', 'Portefeuille citoyen')], max_length=20)),
                ('statut', models.CharField(choices=[('initie', 'Initié'), ('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('echoue', 'Échoué'), ('annule', 'Annulé'), ('rembourse', 'Remboursé'), ('expire', 'Expiré')], default='initie', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('numero_transaction', models.CharField(blank=True, max_length=100)),
                ('code_validation', models.CharField(blank=True, max_length=10)),
                ('reference_bancaire', models.CharField(blank=True, max_length=100)),
                ('preuve_virement', models.FileField(blank=True, null=True, upload_to='preuves_virement/%Y/%m/')),
                ('recu_cash', models.FileField(blank=True, null=True, upload_to='recus_cash/%Y/%m/')),
                ('carte_masquee', models.CharField(blank=True, help_text='Numéro de carte masqué (ex: **** **** **** 1234)', max_length=19)),
                ('carte_token', models.CharField(blank=True, max_length=255)),
                ('message_erreur', models.TextField(blank=True)),
                ('tentative_compteur', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('encaisse_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encaissements', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField()),
                ('montant_rembourse', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20)),
                ('commentaire_moderation', models.TextField(blank=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remboursements_traites', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='paiements.transactionpaiement')),
            ],
            options={
                'verbose_name': 'Remboursement',
                'verbose_name_plural': 'Remboursements',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='RecuPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recu', models.CharField(max_length=50, unique=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='recus_pdf/%Y/%m/')),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='recus_qr/%Y/%m/')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recu', to='paiements.transactionpaiement')),
            ],
            options={
                'verbose_name': 'Reçu de paiement',
                'verbose_name_plural': 'Reçus de paiement',
                'ordering': ['-date_generation'],
            },
        ),
        migrations.CreateModel(
            name='JournalPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('ancien_statut', models.CharField(blank=True, max_length=20, null=True)),
                ('nouveau_statut', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='paiements.transactionpaiement')),
            ],
            options={
                'verbose_name': 'Journal de paiement',
                'verbose_name_plural': 'Journaux de paiement',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='TransactionPortefeuille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('type_transaction', models.CharField(choices=[('credit', 'Crédit'), ('debit', 'Débit')], max_length=20)),
                ('categorie', models.CharField(choices=[('recharge', 'Recharge'), ('paiement', 'Paiement'), ('remboursement', 'Remboursement'), ('cashback', 'Cashback'), ('bonus', 'Bonus')], default='recharge', max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('solde_apres', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('portefeuille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='paiements.portefeuillecitoyen')),
                ('transaction_liee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paiements.transactionpaiement')),
            ],
            options={
                'verbose_name': 'Transaction de portefeuille',
                'verbose_name_plural': 'Transactions de portefeuille',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='WebhookPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('evenement', models.CharField(choices=[('transaction.confirmee', 'Transaction confirmée'), ('transaction.echouee', 'Transaction échouée'), ('transaction.rembourse', 'Transaction remboursée'), ('portefeuille.credite', 'Portefeuille crédité'), ('portefeuille.debite', 'Portefeuille débité')], max_length=50)),
                ('secret', models.CharField(blank=True, max_length=255)),
                ('est_actif', models.BooleanField(default=True)),
                ('tentative_compteur', models.PositiveIntegerField(default=0)),
                ('dernier_envoi', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Webhook de paiement',
                'verbose_name_plural': 'Webhooks de paiement',
                'unique_together': {('url', 'evenement')},
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(default=dict)),
                ('reponse_status', models.IntegerField(blank=True, null=True)),
                ('reponse_body', models.TextField(blank=True)),
                ('erreur', models.TextField(blank=True)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paiements.transactionpaiement')),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='paiements.webhookpaiement')),
            ],
            options={
                'verbose_name': 'Log de webhook',
                'verbose_name_plural': 'Logs de webhook',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.AddIndex(
            model_name='transactionpaiement',
            index=models.Index(fields=['reference'], name='paiements_t_referen_87070d_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionpaiement',
            index=models.Index(fields=['statut', 'mode'], name='paiements_t_statut_a9f388_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionpaiement',
            index=models.Index(fields=['utilisateur', 'date_creation'], name='paiements_t_utilisa_f975cb_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionpaiement',
            index=models.Index(fields=['module_source', 'source_id'], name='paiements_t_module__00fb0b_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionpaiement',
            index=models.Index(fields=['date_expiration'], name='paiements_t_date_ex_06c248_idx'),
        ),
        migrations.AddIndex(
            model_name='journalpaiement',
            index=models.Index(fields=['transaction', 'action'], name='paiements_j_transac_2d5442_idx'),
        ),
        migrations.AddIndex(
            model_name='journalpaiement',
            index=models.Index(fields=['date_action'], name='paiements_j_date_ac_ba45eb_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionportefeuille',
            index=models.Index(fields=['portefeuille', '-date_creation'], name='paiements_t_portefe_03e816_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionportefeuille',
            index=models.Index(fields=['type_transaction', 'categorie'], name='paiements_t_type_tr_46ebd7_idx'),
        ),
    ]
