# Generated by Django 5.2 on 2026-06-12 18:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationTarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_acte', models.CharField(choices=[('naissance', 'Acte de naissance'), ('mariage', 'Acte de mariage'), ('deces', 'Acte de décès'), ('reconnaissance', 'Acte de reconnaissance'), ('adoption', "Acte d'adoption"), ('certificat_vie', 'Certificat de vie'), ('extrait', "Extrait d'acte")], max_length=20, unique=True)),
                ('delai_normal_jours', models.IntegerField(default=45, help_text='Délai normal en jours pour déclaration')),
                ('tarif_normal', models.DecimalField(decimal_places=2, default=1000, help_text='Tarif pour déclaration dans les délais', max_digits=10)),
                ('tarif_retard', models.DecimalField(decimal_places=2, default=10000, help_text='Tarif pour déclaration hors délais', max_digits=10)),
                ('tarif_copie', models.DecimalField(decimal_places=2, default=500, help_text='Tarif pour copie supplémentaire', max_digits=10)),
                ('tarif_extrait', models.DecimalField(decimal_places=2, default=1000, help_text="Tarif pour extrait d'acte", max_digits=10)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration tarifaire',
                'verbose_name_plural': 'Configurations tarifaires',
                'ordering': ['type_acte'],
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('chef_lieu', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('chef_lieu', models.CharField(blank=True, max_length=100)),
                ('population', models.PositiveIntegerField(default=0, help_text='Population estimée')),
            ],
            options={
                'verbose_name': 'Région',
                'verbose_name_plural': 'Régions',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='DemandeActe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('type_acte', models.CharField(choices=[('naissance', 'Acte de naissance'), ('mariage', 'Acte de mariage'), ('deces', 'Acte de décès'), ('reconnaissance', 'Acte de reconnaissance'), ('adoption', "Acte d'adoption"), ('certificat_vie', 'Certificat de vie'), ('extrait', "Extrait d'acte")], max_length=20)),
                ('data_acte', models.JSONField(default=dict)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente de validation'), ('en_cours', 'En cours de traitement'), ('valide_agent', 'Validé par agent'), ('valide_citoyen', 'Validé par citoyen'), ('signe', 'Signé'), ('rejete', 'Rejeté'), ('delivre', 'Délivré'), ('expire', 'Expiré')], default='brouillon', max_length=20)),
                ('commentaire_rejet', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_validation_agent', models.DateTimeField(blank=True, null=True)),
                ('date_validation_citoyen', models.DateTimeField(blank=True, null=True)),
                ('date_signature', models.DateTimeField(blank=True, null=True)),
                ('date_delivrance', models.DateTimeField(blank=True, null=True)),
                ('date_expiration_copie', models.DateTimeField(blank=True, null=True)),
                ('tarif_applique', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('paiement_effectue', models.BooleanField(default=False)),
                ('reference_paiement', models.CharField(blank=True, max_length=100)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='actes_pdf/%Y/%m/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/%Y/%m/')),
                ('piece_identite', models.FileField(blank=True, null=True, upload_to='etat_civil/identite/%Y/%m/')),
                ('justificatif_domicile', models.FileField(blank=True, null=True, upload_to='etat_civil/domicile/%Y/%m/')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('agent_traitant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actes_traites', to=settings.AUTH_USER_MODEL)),
                ('autorite_signataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actes_signes', to=settings.AUTH_USER_MODEL)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_actes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CopieActe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acte_original', models.CharField(help_text="Référence de l'acte original", max_length=50)),
                ('nombre_copies', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('motif', models.TextField(blank=True)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='copie', to='etat_civil.demandeacte')),
            ],
            options={
                'verbose_name': "Copie d'acte",
                'verbose_name_plural': "Copies d'actes",
            },
        ),
        migrations.CreateModel(
            name='CertificatVie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiaire', models.CharField(max_length=200)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=200)),
                ('numero_pension', models.CharField(max_length=50)),
                ('date_validite', models.DateField()),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificat_vie', to='etat_civil.demandeacte')),
            ],
            options={
                'verbose_name': 'Certificat de vie',
                'verbose_name_plural': 'Certificats de vie',
            },
        ),
        migrations.CreateModel(
            name='Arrondissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('chef_lieu', models.CharField(blank=True, max_length=100)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrondissements', to='etat_civil.departement')),
            ],
            options={
                'verbose_name': 'Arrondissement',
                'verbose_name_plural': 'Arrondissements',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='DistrictSante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('arrondissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts_sante', to='etat_civil.arrondissement')),
            ],
            options={
                'verbose_name': 'District de santé',
                'verbose_name_plural': 'Districts de santé',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueStatut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(max_length=20)),
                ('nouveau_statut', models.CharField(max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='etat_civil.demandeacte')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de statut',
                'verbose_name_plural': 'Historiques de statut',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='NotificationActe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('est_lue', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='etat_civil.demandeacte')),
            ],
            options={
                'verbose_name': "Notification d'acte",
                'verbose_name_plural': "Notifications d'actes",
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.AddField(
            model_name='departement',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='etat_civil.region'),
        ),
        migrations.AddIndex(
            model_name='demandeacte',
            index=models.Index(fields=['reference'], name='etat_civil__referen_e22260_idx'),
        ),
        migrations.AddIndex(
            model_name='demandeacte',
            index=models.Index(fields=['statut', 'type_acte'], name='etat_civil__statut_7b86da_idx'),
        ),
        migrations.AddIndex(
            model_name='demandeacte',
            index=models.Index(fields=['demandeur', 'statut'], name='etat_civil__demande_712eef_idx'),
        ),
        migrations.AddIndex(
            model_name='demandeacte',
            index=models.Index(fields=['date_creation'], name='etat_civil__date_cr_0787b4_idx'),
        ),
        migrations.AddIndex(
            model_name='historiquestatut',
            index=models.Index(fields=['demande', 'date'], name='etat_civil__demande_e5b9f8_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationacte',
            index=models.Index(fields=['demande', 'est_lue'], name='etat_civil__demande_0c8563_idx'),
        ),
    ]
