# Generated by Django 5.2 on 2026-06-12 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('est_lue', models.BooleanField(default=False)),
                ('lien', models.CharField(blank=True, max_length=500)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_agent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='TacheAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_tache', models.CharField(choices=[('etat_civil', 'État Civil'), ('dechets', 'Déchets'), ('archives', 'Archives'), ('paiements', 'Paiements'), ('signature', 'Signature')], max_length=20)),
                ('priorite', models.CharField(choices=[('haute', '🔴 Haute'), ('moyenne', '🟠 Moyenne'), ('basse', '🟢 Basse')], default='moyenne', max_length=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('reference_id', models.CharField(blank=True, help_text='ID de la demande liée', max_length=100)),
                ('lien_demande', models.CharField(blank=True, max_length=500)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_echeance', models.DateTimeField()),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('commentaire_traitement', models.TextField(blank=True)),
                ('assigne_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to=settings.AUTH_USER_MODEL)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priorite', 'date_echeance'],
            },
        ),
    ]
