# Generated by Django 5.2 on 2026-06-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('total_actes', models.IntegerField(default=0)),
                ('total_inscriptions', models.IntegerField(default=0)),
                ('total_signalements', models.IntegerField(default=0)),
                ('total_transactions', models.IntegerField(default=0)),
                ('total_archives', models.IntegerField(default=0)),
                ('total_structures', models.IntegerField(default=0)),
                ('total_actualites', models.IntegerField(default=0)),
                ('total_signatures', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Statistique',
                'verbose_name_plural': 'Statistiques',
                'ordering': ['-date'],
            },
        ),
    ]
