# Generated by Django 5.2 on 2026-06-12 18:16

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieActualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Classe FontAwesome', max_length=50)),
                ('couleur', models.CharField(default='#2563eb', help_text='Couleur hexadécimale', max_length=20)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('accroche', models.CharField(help_text="Résumé accrocheur de l'article", max_length=300)),
                ('contenu', django_ckeditor_5.fields.CKEditor5Field(help_text="Contenu complet de l'actualité")),
                ('type_media', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo'), ('aucun', 'Aucun média')], default='image', max_length=10)),
                ('media', models.FileField(blank=True, null=True, upload_to='actualites/media/%Y/%m/')),
                ('media_url', models.URLField(blank=True, help_text='URL externe pour vidéo (YouTube, Vimeo)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='actualites/thumbnails/%Y/%m/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_moderation', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis à modération'), ('en_correction', 'En correction'), ('publie', 'Publié'), ('rejete', 'Rejeté'), ('archive', 'Archivé')], default='brouillon', max_length=20)),
                ('est_epingle', models.BooleanField(default=False)),
                ('est_a_la_une', models.BooleanField(default=False)),
                ('vue_count', models.PositiveIntegerField(default=0)),
                ('partage_count', models.PositiveIntegerField(default=0)),
                ('commentaire_moderation', models.TextField(blank=True, help_text='Commentaire du modérateur')),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('mots_cles_seo', models.CharField(blank=True, max_length=200)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='actualites.categorieactualite')),
                ('moderateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications_moderees', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-est_epingle', '-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='PropositionCitoyenne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire_reponse', models.TextField(blank=True, null=True)),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de modération'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('publiee', 'Publiée')], default='en_attente', max_length=20)),
                ('commentaire_moderation', models.TextField(blank=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions', to=settings.AUTH_USER_MODEL)),
                ('publication_associee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='actualites.publication')),
            ],
            options={
                'verbose_name': 'Proposition citoyenne',
                'verbose_name_plural': 'Propositions citoyennes',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='Partage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plateforme', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('lien', 'Lien externe')], max_length=50)),
                ('date_partage', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partages', to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partages', to='actualites.publication')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_actualites', to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actualites.publication')),
            ],
            options={
                'ordering': ['-date_consultation'],
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(max_length=1000)),
                ('est_approuve', models.BooleanField(default=False)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='actualites.commentaire')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_actualites', to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='actualites.publication')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_reaction', models.CharField(choices=[('like', "👍 J'aime"), ('love', "❤️ J'adore"), ('laugh', '😄 Ha ha'), ('wow', '😮 Wow'), ('sad', '😢 Triste'), ('angry', '😠 En colère')], max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='actualites.publication')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['statut', 'date_publication'], name='actualites__statut_5110e2_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['categorie', 'statut'], name='actualites__categor_f56699_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['-date_publication'], name='actualites__date_pu_e5f693_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='partage',
            unique_together={('publication', 'utilisateur', 'plateforme')},
        ),
        migrations.AlterUniqueTogether(
            name='historiqueconsultation',
            unique_together={('utilisateur', 'publication')},
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['publication', 'type_reaction'], name='actualites__publica_b483d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('publication', 'utilisateur')},
        ),
    ]
