# Generated by Django 5.2 on 2026-06-12 18:16

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('icon', models.CharField(default='fas fa-building', max_length=50)),
                ('couleur', models.CharField(default='#667eea', max_length=20)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Elu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('fonction', models.CharField(choices=[('maire', 'Maire'), ('adjoint', 'Adjoint au maire'), ('conseiller', 'Conseiller municipal'), ('president', 'Président de commission'), ('autre', 'Autre')], default='conseiller', max_length=50)),
                ('titre', models.CharField(blank=True, help_text='Titre spécifique (ex: Maire de Douala)', max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='elus/%Y/')),
                ('biographie', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('commission', models.CharField(blank=True, help_text='Commission rattachée', max_length=200)),
                ('delegation', models.CharField(blank=True, max_length=200)),
                ('parti', models.CharField(blank=True, max_length=100)),
                ('date_debut_mandat', models.DateField(blank=True, null=True)),
                ('date_fin_mandat', models.DateField(blank=True, null=True)),
                ('ordre', models.IntegerField(default=0)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Élu',
                'verbose_name_plural': 'Élus',
                'ordering': ['ordre', 'fonction', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('type_structure', models.CharField(choices=[('mairie', '🏛️ Mairie / Mairie annexe'), ('ecole', '🏫 École / Université'), ('hopital', '🏥 Hôpital / Centre de santé'), ('marche', '🛒 Marché / Commerce'), ('police', '👮 Commissariat / Gendarmerie'), ('transport', '🚌 Transport / Gare'), ('culture', '🎭 Centre culturel / Bibliothèque'), ('sport', '⚽ Complexe sportif'), ('social', '🤝 Centre social'), ('religion', '⛪ Lieu de culte'), ('autre', '📌 Autre')], default='autre', max_length=20)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('adresse', models.TextField()),
                ('quartier', models.CharField(blank=True, max_length=100)),
                ('ville', models.CharField(default='Douala', max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('telephone2', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp', models.CharField(blank=True, help_text='Numéro WhatsApp', max_length=50)),
                ('site_web', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('horaires_lundi', models.CharField(blank=True, max_length=200)),
                ('horaires_mardi', models.CharField(blank=True, max_length=200)),
                ('horaires_mercredi', models.CharField(blank=True, max_length=200)),
                ('horaires_jeudi', models.CharField(blank=True, max_length=200)),
                ('horaires_vendredi', models.CharField(blank=True, max_length=200)),
                ('horaires_samedi', models.CharField(blank=True, max_length=200)),
                ('horaires_dimanche', models.CharField(blank=True, max_length=200)),
                ('horaires_speciaux', models.TextField(blank=True, help_text='Horaires spéciaux (jours fériés, etc.)')),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='annuaire/%Y/%m/')),
                ('images_galerie', models.JSONField(blank=True, default=list)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('ferme', 'Fermé temporairement'), ('en_construction', 'En construction'), ('inactif', 'Inactif')], default='actif', max_length=20)),
                ('est_populaire', models.BooleanField(default=False)),
                ('est_verifie', models.BooleanField(default=False)),
                ('vue_count', models.PositiveIntegerField(default=0)),
                ('contact_count', models.PositiveIntegerField(default=0)),
                ('favori_count', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='annuaires.categoriestructure')),
            ],
            options={
                'verbose_name': 'Structure',
                'verbose_name_plural': 'Structures',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='FavoriStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris_annuaire', to=settings.AUTH_USER_MODEL)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='annuaires.structure')),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='ContactStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(choices=[('information', "Demande d'information"), ('rdv', 'Prise de rendez-vous'), ('reclamation', 'Réclamation'), ('suggestion', 'Suggestion'), ('autre', 'Autre')], max_length=50)),
                ('message', models.TextField()),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('est_traite', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='annuaires.structure')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='AvisStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.TextField()),
                ('est_approuve', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_structures', to=settings.AUTH_USER_MODEL)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='annuaires.structure')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddIndex(
            model_name='structure',
            index=models.Index(fields=['type_structure', 'ville'], name='annuaires_s_type_st_3dcd93_idx'),
        ),
        migrations.AddIndex(
            model_name='structure',
            index=models.Index(fields=['latitude', 'longitude'], name='annuaires_s_latitud_87abef_idx'),
        ),
        migrations.AddIndex(
            model_name='structure',
            index=models.Index(fields=['est_populaire'], name='annuaires_s_est_pop_12b597_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favoristructure',
            unique_together={('utilisateur', 'structure')},
        ),
    ]
