# Generated by Django 5.2 on 2026-06-12 18:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('couleur', models.CharField(default='#6c757d', help_text='Code hexadécimal (ex: #6c757d)', max_length=7)),
                ('icone', models.CharField(default='archive', help_text="Nom de l'icône FontAwesome/Bootstrap", max_length=50)),
                ('ordre', models.IntegerField(default=0)),
                ('est_actif', models.BooleanField(default=True)),
                ('meta_description', models.CharField(blank=True, max_length=200)),
                ('meta_keywords', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': "Catégorie d'archive",
                'verbose_name_plural': "Catégories d'archives",
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('mots_cles', models.CharField(blank=True, help_text='Mots-clés séparés par des virgules', max_length=500)),
                ('date_document', models.DateField(help_text='Date du document original')),
                ('date_archivage', models.DateField(auto_now_add=True)),
                ('periode_debut', models.DateField(blank=True, null=True)),
                ('periode_fin', models.DateField(blank=True, null=True)),
                ('auteur', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('emplacement_physique', models.CharField(blank=True, max_length=200)),
                ('numero_boite', models.CharField(blank=True, max_length=50)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='archives/documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('vignette', models.ImageField(blank=True, null=True, upload_to='archives/vignettes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('fichiers_annexes', models.JSONField(blank=True, default=list)),
                ('taille_fichier', models.BigIntegerField(default=0, help_text='Taille en octets')),
                ('nombre_pages', models.PositiveIntegerField(default=0, help_text='Nombre de pages du document')),
                ('duree_conservation', models.CharField(choices=[('permanent', 'Conservation permanente'), ('10_ans', '10 ans'), ('20_ans', '20 ans'), ('30_ans', '30 ans'), ('50_ans', '50 ans'), ('100_ans', '100 ans')], default='permanent', max_length=20)),
                ('date_fin_conservation', models.DateField(blank=True, null=True)),
                ('niveau_acces', models.CharField(choices=[('public', 'Public - Accès libre'), ('restreint', 'Restreint - Sur demande'), ('confidentiel', 'Confidentiel - Autorisation requise'), ('tres_confidentiel', 'Très confidentiel - Cadres uniquement')], default='public', max_length=20)),
                ('payant', models.BooleanField(default=False)),
                ('tarif', models.DecimalField(decimal_places=2, default=0, help_text='Tarif standard', max_digits=10)),
                ('tarif_consultation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tarif_impression', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tarif_copie', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tarif_envoi', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('pret', 'En prêt'), ('restauration', 'En restauration'), ('perdu', 'Perdu'), ('numerise', 'Numérisé'), ('archive', 'Archivé')], default='disponible', max_length=20)),
                ('vues', models.PositiveIntegerField(default=0)),
                ('telechargements', models.PositiveIntegerField(default=0)),
                ('demandes_acces', models.PositiveIntegerField(default=0)),
                ('note_moyenne', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='archives.categoriearchive')),
            ],
            options={
                'ordering': ['-date_document'],
            },
        ),
        migrations.CreateModel(
            name='DemandeAccesArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_demande', models.CharField(choices=[('consultation', 'Consultation sur place'), ('copie', 'Copie numérique'), ('impression', 'Impression papier'), ('envoi', 'Envoi par courrier')], max_length=20)),
                ('motif', models.TextField()),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='archives/justificatifs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('adresse_livraison', models.TextField(blank=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('en_cours', 'En cours de traitement'), ('valide', 'Validée - En attente de paiement'), ('paye', 'Payée - En traitement'), ('pret', 'Prête - Disponible'), ('rejetee', 'Rejetée'), ('livree', 'Livrée'), ('cloturee', 'Clôturée'), ('expiree', 'Expirée')], default='en_attente', max_length=20)),
                ('commentaire_moderation', models.TextField(blank=True)),
                ('date_moderation', models.DateTimeField(blank=True, null=True)),
                ('paiement_effectue', models.BooleanField(default=False)),
                ('reference_paiement', models.CharField(blank=True, max_length=100)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('moyen_paiement', models.CharField(blank=True, help_text='Carte, Mobile Money, etc.', max_length=50)),
                ('date_debut_acces', models.DateTimeField(blank=True, null=True)),
                ('date_fin_acces', models.DateTimeField(blank=True, null=True)),
                ('lien_acces', models.CharField(blank=True, help_text='Lien temporaire pour téléchargement', max_length=500)),
                ('token_acces', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('telechargements_effectues', models.PositiveIntegerField(default=0)),
                ('notification_envoyee', models.BooleanField(default=False)),
                ('date_notification', models.DateTimeField(blank=True, null=True)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='archives.archive')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_archives', to=settings.AUTH_USER_MODEL)),
                ('moderateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueConsultationArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('temps_consulte', models.PositiveIntegerField(default=0, help_text='Temps de consultation en secondes')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='archives.archive')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_archives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_consultation'],
            },
        ),
        migrations.CreateModel(
            name='LogArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='archives.archive')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='PretArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateTimeField(auto_now_add=True)),
                ('date_retour_prevue', models.DateField()),
                ('date_retour_effective', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('retard', 'En retard'), ('retourne', 'Retourné'), ('perdu', 'Perdu')], default='en_cours', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prets', to='archives.archive')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prets_archives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Prêt d'archive",
                'verbose_name_plural': "Prêts d'archives",
                'ordering': ['-date_emprunt'],
            },
        ),
        migrations.CreateModel(
            name='AvisArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(help_text='Note de 1 à 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.TextField(blank=True, max_length=1000)),
                ('est_approuve', models.BooleanField(default=False, help_text='Approuvé par un modérateur')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='archives.archive')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_archives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['archive', 'est_approuve'], name='archives_av_archive_d71bf7_idx'), models.Index(fields=['utilisateur'], name='archives_av_utilisa_c0116a_idx')],
                'unique_together': {('archive', 'utilisateur')},
            },
        ),
        migrations.AddIndex(
            model_name='archive',
            index=models.Index(fields=['categorie', 'niveau_acces'], name='archives_ar_categor_e598fa_idx'),
        ),
        migrations.AddIndex(
            model_name='archive',
            index=models.Index(fields=['reference'], name='archives_ar_referen_08a059_idx'),
        ),
        migrations.AddIndex(
            model_name='archive',
            index=models.Index(fields=['mots_cles'], name='archives_ar_mots_cl_519133_idx'),
        ),
        migrations.AddIndex(
            model_name='archive',
            index=models.Index(fields=['date_document'], name='archives_ar_date_do_89b982_idx'),
        ),
        migrations.AddIndex(
            model_name='archive',
            index=models.Index(fields=['statut'], name='archives_ar_statut_514ba3_idx'),
        ),
        migrations.AddIndex(
            model_name='archive',
            index=models.Index(fields=['-date_archivage'], name='archives_ar_date_ar_f5371f_idx'),
        ),
        migrations.AddIndex(
            model_name='demandeaccesarchive',
            index=models.Index(fields=['statut', 'date_demande'], name='archives_de_statut_e77813_idx'),
        ),
        migrations.AddIndex(
            model_name='demandeaccesarchive',
            index=models.Index(fields=['token_acces'], name='archives_de_token_a_a376d9_idx'),
        ),
        migrations.AddIndex(
            model_name='demandeaccesarchive',
            index=models.Index(fields=['demandeur', 'statut'], name='archives_de_demande_afe5d2_idx'),
        ),
        migrations.AddIndex(
            model_name='historiqueconsultationarchive',
            index=models.Index(fields=['archive', '-date_consultation'], name='archives_hi_archive_7b6ece_idx'),
        ),
        migrations.AddIndex(
            model_name='historiqueconsultationarchive',
            index=models.Index(fields=['utilisateur', '-date_consultation'], name='archives_hi_utilisa_a670f9_idx'),
        ),
        migrations.AddIndex(
            model_name='logarchive',
            index=models.Index(fields=['action', '-date_action'], name='archives_lo_action_60f588_idx'),
        ),
        migrations.AddIndex(
            model_name='logarchive',
            index=models.Index(fields=['archive', '-date_action'], name='archives_lo_archive_2d384d_idx'),
        ),
    ]
