# Generated by Django 5.2 on 2026-06-12 18:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fas fa-calendar-alt', max_length=50)),
                ('couleur', models.CharField(default='#667eea', max_length=20)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('type_activite', models.CharField(choices=[('sante', '🏥 Campagne de santé'), ('formation', '📚 Formation'), ('culturel', '🎭 Événement culturel'), ('sportif', '⚽ Événement sportif'), ('social', '🤝 Action sociale'), ('environnement', '🌱 Environnement'), ('citoyen', '🗳️ Réunion citoyenne'), ('autre', '📌 Autre')], default='autre', max_length=20)),
                ('description_courte', models.CharField(max_length=300)),
                ('description_longue', django_ckeditor_5.fields.CKEditor5Field()),
                ('image_principale', models.ImageField(upload_to='activites/%Y/%m/')),
                ('images_galerie', models.JSONField(blank=True, default=list)),
                ('video_url', models.URLField(blank=True, help_text='Lien YouTube/Vimeo')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('date_limite_inscription', models.DateTimeField()),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('capacite_max', models.PositiveIntegerField(default=0, help_text='0 = illimité')),
                ('prix', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('est_gratuit', models.BooleanField(default=True)),
                ('lieu', models.CharField(max_length=300)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('coordonnees_gps', models.CharField(blank=True, help_text='Latitude,Longitude', max_length=100)),
                ('partenaires', models.TextField(blank=True, help_text='Liste des partenaires')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('complet', 'Complet'), ('annule', 'Annulé'), ('termine', 'Terminé')], default='brouillon', max_length=20)),
                ('est_a_la_une', models.BooleanField(default=False)),
                ('est_recommandee', models.BooleanField(default=False)),
                ('vue_count', models.PositiveIntegerField(default=0)),
                ('partage_count', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('organisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites_organisees', to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activites.categorieactivite')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('nom_complet', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=50)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('adresse', models.TextField(blank=True)),
                ('commentaire', models.TextField(blank=True)),
                ('nombre_places', models.PositiveIntegerField(default=1)),
                ('noms_accompagnants', models.TextField(blank=True, help_text='Noms des personnes accompagnantes')),
                ('montant_total', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('moyen_paiement', models.CharField(blank=True, choices=[('mtn', 'MTN Mobile Money'), ('orange', 'Orange Money'), ('carte', 'Carte bancaire'), ('especes', 'Espèces'), ('virement', 'Virement bancaire')], max_length=50)),
                ('reference_paiement', models.CharField(blank=True, max_length=100)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente_paiement', 'En attente de paiement'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('present', 'Présent'), ('absent', 'Absent')], default='en_attente_paiement', max_length=30)),
                ('qr_code', models.TextField(blank=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_annulation', models.DateTimeField(blank=True, null=True)),
                ('date_presence', models.DateTimeField(blank=True, null=True)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='activites.activite')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_activites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='AvisActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.TextField()),
                ('est_approuve', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='activites.inscription')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
            },
        ),
        migrations.CreateModel(
            name='NotificationActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('inscription', "Confirmation d'inscription"), ('rappel', "Rappel d'événement"), ('annulation', 'Annulation'), ('modification', 'Modification'), ('info', 'Information')], max_length=20)),
                ('canal', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Notification push')], max_length=10)),
                ('sujet', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('est_envoyee', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('activite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activites.activite')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_activites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaiementActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('moyen_paiement', models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('orange', 'Orange Money'), ('carte', 'Carte bancaire'), ('especes', 'Espèces'), ('virement', 'Virement bancaire')], max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('numero_telephone', models.CharField(blank=True, max_length=50)),
                ('operator', models.CharField(blank=True, max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('api_response', models.JSONField(blank=True, default=dict)),
                ('inscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='activites.inscription')),
            ],
        ),
        migrations.AddIndex(
            model_name='activite',
            index=models.Index(fields=['statut', 'date_debut'], name='activites_a_statut_290025_idx'),
        ),
        migrations.AddIndex(
            model_name='activite',
            index=models.Index(fields=['type_activite'], name='activites_a_type_ac_96d655_idx'),
        ),
        migrations.AddIndex(
            model_name='activite',
            index=models.Index(fields=['est_a_la_une'], name='activites_a_est_a_l_f1e79f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together={('activite', 'utilisateur')},
        ),
    ]
