# Generated by Django 5.2 on 2026-06-12 18:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraireOptimise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_totale', models.FloatField(default=0, help_text='Distance en km')),
                ('duree_estimee', models.IntegerField(default=0, help_text='Durée en minutes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Itinéraire optimisé',
                'verbose_name_plural': 'Itinéraires optimisés',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PointCollecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('type', models.CharField(choices=[('bac_240', 'Bac 240L'), ('bac_660', 'Bac 660L'), ('bac_1100', 'Bac 1100L'), ('container', 'Container'), ('point_tri', 'Point de tri sélectif')], default='bac_240', max_length=20)),
                ('adresse_reference', models.CharField(help_text="Ex: 'Près de l'église de Ndikinimeki'", max_length=300)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='dechets/bacs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('capacite_kg', models.PositiveIntegerField(default=240, help_text='Capacité en kg')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('plein', 'Plein - nécessite vidage'), ('casse', 'Cassé'), ('en_maintenance', 'En maintenance'), ('supprime', 'Supprimé')], default='actif', max_length=20)),
                ('dernier_vidage', models.DateTimeField(blank=True, null=True)),
                ('prochain_vidage', models.DateTimeField(blank=True, null=True)),
                ('niveau_remplissage', models.PositiveSmallIntegerField(default=0, help_text='Pourcentage estimé de remplissage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('signalements_count', models.PositiveIntegerField(default=0)),
                ('collectes_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Point de collecte',
                'verbose_name_plural': 'Points de collecte',
            },
        ),
        migrations.CreateModel(
            name='ItinerairePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField()),
                ('itineraire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dechets.itineraireoptimise')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dechets.pointcollecte')),
            ],
            options={
                'ordering': ['ordre'],
                'unique_together': {('itineraire', 'point')},
            },
        ),
        migrations.AddField(
            model_name='itineraireoptimise',
            name='points',
            field=models.ManyToManyField(through='dechets.ItinerairePoint', to='dechets.pointcollecte'),
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('ordre', models.IntegerField(default=0)),
                ('code_postal', models.CharField(blank=True, help_text='Code postal du quartier', max_length=10)),
                ('population_estimee', models.PositiveIntegerField(default=0, help_text='Population estimée du quartier')),
                ('couleur', models.CharField(default='#28a745', help_text='Couleur hexadécimale', max_length=7)),
            ],
            options={
                'verbose_name': 'Quartier',
                'verbose_name_plural': 'Quartiers',
                'ordering': ['ordre', 'nom'],
                'indexes': [models.Index(fields=['slug'], name='dechets_qua_slug_a20931_idx'), models.Index(fields=['nom'], name='dechets_qua_nom_f89d09_idx')],
            },
        ),
        migrations.AddField(
            model_name='pointcollecte',
            name='quartier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_collecte', to='dechets.quartier'),
        ),
        migrations.CreateModel(
            name='NotificationDechet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rappel_collecte', 'Rappel de collecte'), ('alerte_signalement', 'Alerte signalement traité'), ('info_tri', 'Information tri'), ('modification_horaire', 'Modification horaire')], max_length=30)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('est_envoyee', models.BooleanField(default=False)),
                ('envoyer_sms', models.BooleanField(default=True)),
                ('envoyer_email', models.BooleanField(default=False)),
                ('envoyer_push', models.BooleanField(default=True)),
                ('date_planifiee', models.DateTimeField(blank=True, null=True)),
                ('quartier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='dechets.quartier')),
            ],
            options={
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.AddField(
            model_name='itineraireoptimise',
            name='quartier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraires', to='dechets.quartier'),
        ),
        migrations.CreateModel(
            name='CalendrierCollecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('heure_passage', models.TimeField()),
                ('type_dechet', models.CharField(choices=[('ordures_menageres', 'Ordures ménagères'), ('plastiques', 'Plastiques'), ('verre', 'Verre'), ('papiers', 'Papiers/Cartons'), ('dechets_verts', 'Déchets verts'), ('encombrants', 'Encombrants')], default='ordures_menageres', max_length=50)),
                ('est_semaine_impaire', models.BooleanField(default=False, help_text='Si True, collecte uniquement les semaines impaires')),
                ('est_actif', models.BooleanField(default=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('quartier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendriers', to='dechets.quartier')),
            ],
            options={
                'verbose_name': 'Calendrier de collecte',
                'verbose_name_plural': 'Calendriers de collecte',
                'ordering': ['quartier', 'jour_semaine', 'heure_passage'],
            },
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_signalement', models.CharField(choices=[('bac_plein', '🗑️ Bac plein'), ('bac_debordant', '⚠️ Bac débordant'), ('bac_casse', '🔨 Bac cassé'), ('depot_sauvage', '🚯 Dépôt sauvage'), ('odeur', '👃 Nuisance odorante'), ('autre', '📌 Autre')], max_length=20)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='dechets/signalements/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('adresse_description', models.CharField(help_text="Description du lieu (ex: 'près du grand arbre')", max_length=300)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('nom_citoyen', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de traitement'), ('en_cours', 'En cours de traitement'), ('traite', 'Traité'), ('rejete', 'Rejeté'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('commentaire_traitement', models.TextField(blank=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=10)),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('agent_traitement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_traites', to=settings.AUTH_USER_MODEL)),
                ('citoyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements', to=settings.AUTH_USER_MODEL)),
                ('point_collecte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements', to='dechets.pointcollecte')),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'ordering': ['-date_signalement'],
            },
        ),
        migrations.CreateModel(
            name='StatsCollecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('tonnes_collectees', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bacs_vides', models.PositiveIntegerField(default=0)),
                ('signalements_traites', models.PositiveIntegerField(default=0)),
                ('encombrants_collectes', models.PositiveIntegerField(default=0)),
                ('carburant_consomme', models.FloatField(default=0, help_text='Litres de carburant consommés')),
                ('kilometres_parcourus', models.FloatField(default=0, help_text='Kilomètres parcourus')),
                ('agents_mobilises', models.PositiveIntegerField(default=0)),
                ('tournees_completees', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Statistique collecte',
                'verbose_name_plural': 'Statistiques collectes',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='dechets_sta_date_c809c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tournee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ordre_points', models.JSONField(blank=True, default=list, help_text="Liste des IDs dans l'ordre")),
                ('distance_totale', models.FloatField(default=0, help_text='Distance en km')),
                ('duree_estimee', models.IntegerField(default=0, help_text='Durée en minutes')),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin_estimee', models.TimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('debut_reel', models.DateTimeField(blank=True, null=True)),
                ('fin_reelle', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournees', to=settings.AUTH_USER_MODEL)),
                ('quartier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournees', to='dechets.quartier')),
            ],
            options={
                'verbose_name': 'Tournée',
                'verbose_name_plural': 'Tournées',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TourneePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField()),
                ('est_vide', models.BooleanField(default=False)),
                ('photo_preuve', models.ImageField(blank=True, null=True, upload_to='dechets/preuves/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('heure_passage', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dechets.pointcollecte')),
                ('tournee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourneepoint_set', to='dechets.tournee')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.AddField(
            model_name='tournee',
            name='points_collecte',
            field=models.ManyToManyField(through='dechets.TourneePoint', to='dechets.pointcollecte'),
        ),
        migrations.CreateModel(
            name='DemandeEncombrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_encombrant', models.CharField(choices=[('meuble', '🪑 Meuble'), ('electromenager', '🔌 Électroménager'), ('frigo', '❄️ Réfrigérateur'), ('matelas', '🛏️ Matelas'), ('dechets_vert', '🌿 Déchets verts'), ('gravats', '🏗️ Gravats'), ('autre', '📦 Autre')], max_length=20)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='dechets/encombrants/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('adresse', models.CharField(max_length=300)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('point_repere', models.CharField(blank=True, help_text="Point de repère (ex: 'devant la case jaune')", max_length=200)),
                ('date_souhaitee', models.DateField()),
                ('creneau_horaire', models.CharField(blank=True, max_length=100)),
                ('quantite_estimee', models.CharField(choices=[('petit', 'Petit (1-2 objets)'), ('moyen', 'Moyen (3-5 objets)'), ('grand', 'Grand (6+ objets)')], default='moyen', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('planifiee', 'Planifiée'), ('effectuee', 'Effectuée'), ('annulee', 'Annulée'), ('reportee', 'Reportée')], default='en_attente', max_length=20)),
                ('date_planification', models.DateTimeField(blank=True, null=True)),
                ('date_realisation', models.DateTimeField(blank=True, null=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('agent_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encombrants_assignes', to=settings.AUTH_USER_MODEL)),
                ('citoyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_encombrants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Demande d'encombrant",
                'verbose_name_plural': "Demandes d'encombrants",
                'ordering': ['-date_demande'],
                'indexes': [models.Index(fields=['statut', '-date_demande'], name='dechets_dem_statut_634f12_idx'), models.Index(fields=['date_souhaitee'], name='dechets_dem_date_so_5bef57_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='pointcollecte',
            index=models.Index(fields=['code'], name='dechets_poi_code_f49c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='pointcollecte',
            index=models.Index(fields=['statut', 'quartier'], name='dechets_poi_statut_0ce32e_idx'),
        ),
        migrations.AddIndex(
            model_name='pointcollecte',
            index=models.Index(fields=['prochain_vidage'], name='dechets_poi_prochai_52ba81_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdechet',
            index=models.Index(fields=['quartier', 'est_envoyee'], name='dechets_not_quartie_18152f_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdechet',
            index=models.Index(fields=['date_planifiee'], name='dechets_not_date_pl_2373c5_idx'),
        ),
        migrations.AddIndex(
            model_name='calendriercollecte',
            index=models.Index(fields=['quartier', 'est_actif'], name='dechets_cal_quartie_2a8d49_idx'),
        ),
        migrations.AddIndex(
            model_name='calendriercollecte',
            index=models.Index(fields=['jour_semaine', 'type_dechet'], name='dechets_cal_jour_se_60d596_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calendriercollecte',
            unique_together={('quartier', 'jour_semaine', 'type_dechet')},
        ),
        migrations.AddIndex(
            model_name='signalement',
            index=models.Index(fields=['statut', '-date_signalement'], name='dechets_sig_statut_848ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='signalement',
            index=models.Index(fields=['type_signalement', 'statut'], name='dechets_sig_type_si_37424d_idx'),
        ),
        migrations.AddIndex(
            model_name='signalement',
            index=models.Index(fields=['priorite'], name='dechets_sig_priorit_7f8cce_idx'),
        ),
        migrations.AddIndex(
            model_name='tourneepoint',
            index=models.Index(fields=['tournee', 'ordre'], name='dechets_tou_tournee_54e233_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tourneepoint',
            unique_together={('tournee', 'point')},
        ),
        migrations.AddIndex(
            model_name='tournee',
            index=models.Index(fields=['date', 'statut'], name='dechets_tou_date_b5dded_idx'),
        ),
        migrations.AddIndex(
            model_name='tournee',
            index=models.Index(fields=['quartier', 'date'], name='dechets_tou_quartie_7f3a48_idx'),
        ),
    ]
